import { doublingTenureYears } from './calculators';
import { DepositScheme, RateSlab } from './models';

// Standard term deposit ladder — see docs/deposit-schemes.md for the source table.
const LADDER_SLABS: RateSlab[] = [
  { minDays: 7, maxDays: 30, label: '7-30 Days', rates: { normal: 3.75, senior: 4.35, superSenior: 4.5 } },
  { minDays: 31, maxDays: 45, label: '31-45 Days', rates: { normal: 3.75, senior: 4.35, superSenior: 4.5 } },
  { minDays: 46, maxDays: 90, label: '46-90 Days', rates: { normal: 4.5, senior: 5.1, superSenior: 5.25 } },
  { minDays: 91, maxDays: 179, label: '91-179 Days', rates: { normal: 4.75, senior: 5.35, superSenior: 5.5 } },
  { minDays: 180, maxDays: 270, label: '180-270 Days', rates: { normal: 6.0, senior: 6.6, superSenior: 6.75 } },
  { minDays: 271, maxDays: 364, label: '271-364 Days', rates: { normal: 6.0, senior: 6.6, superSenior: 6.75 } },
  { minDays: 365, maxDays: 730, label: '1-2 Years', rates: { normal: 7.0, senior: 7.6, superSenior: 7.75 } },
  { minDays: 731, maxDays: 1095, label: '2-3 Years', rates: { normal: 7.25, senior: 7.85, superSenior: 8.0 } },
  { minDays: 1096, maxDays: 1825, label: '3-5 Years', rates: { normal: 7.9, senior: 8.5, superSenior: 8.65 } },
  { minDays: 1826, maxDays: 3650, label: '5+ Years', rates: { normal: 7.25, senior: 7.85, superSenior: 8.0 } },
];

const DOUBLE_PLUS_RATE = 8.1;
const DOUBLE_PLUS_TENURE_DAYS = Math.round(doublingTenureYears(DOUBLE_PLUS_RATE) * 365);

export const DEPOSIT_SCHEMES: DepositScheme[] = [
  {
    id: 'term-ladder',
    name: 'Term Deposit',
    calcType: 'FD_LADDER',
    supportsCustomerType: true,
    slabs: LADDER_SLABS,
    minTenureDays: 7,
    maxTenureDays: 3650,
    minAmount: 5000,
    maxAmount: 1000000,
    defaultAmount: 100000,
    amountStep: 5000,
    amountLabel: 'Deposit Amount',
  },
  {
    id: 'mnsn-333',
    name: 'MNSN Deposit — 333 Days',
    calcType: 'FD_FIXED',
    supportsCustomerType: true,
    fixedTenureDays: 333,
    rates: { normal: 7.0, senior: 7.6, superSenior: 7.75 },
    minAmount: 5000,
    maxAmount: 1000000,
    defaultAmount: 100000,
    amountStep: 5000,
    amountLabel: 'Deposit Amount',
  },
  {
    id: 'mnsn-666',
    name: 'MNSN Deposit — 666 Days',
    calcType: 'FD_FIXED',
    supportsCustomerType: true,
    fixedTenureDays: 666,
    rates: { normal: 8.1, senior: 8.7, superSenior: 8.85 },
    minAmount: 5000,
    maxAmount: 1000000,
    defaultAmount: 100000,
    amountStep: 5000,
    amountLabel: 'Deposit Amount',
  },
  {
    id: 'double-plus',
    name: 'Double Plus Deposit',
    calcType: 'DOUBLING',
    supportsCustomerType: false,
    fixedTenureDays: DOUBLE_PLUS_TENURE_DAYS,
    rates: { normal: DOUBLE_PLUS_RATE, senior: DOUBLE_PLUS_RATE, superSenior: DOUBLE_PLUS_RATE },
    minAmount: 5000,
    maxAmount: 1000000,
    defaultAmount: 100000,
    amountStep: 5000,
    amountLabel: 'Deposit Amount',
  },
  {
    id: 'rd-bb-nidhi',
    name: 'RD BB Nidhi',
    calcType: 'RD',
    supportsCustomerType: false,
    fixedTenureDays: 365,
    rates: { normal: 7.31, senior: null, superSenior: null },
    minAmount: 500,
    maxAmount: 50000,
    defaultAmount: 2000,
    amountStep: 500,
    amountLabel: 'Monthly Installment',
  },
  {
    id: 'spl-rd-1y',
    name: 'SPL RD — 1 Year',
    calcType: 'RD',
    supportsCustomerType: true,
    fixedTenureDays: 365,
    rates: { normal: 7.25, senior: 7.85, superSenior: 8.0 },
    minAmount: 500,
    maxAmount: 50000,
    defaultAmount: 2000,
    amountStep: 500,
    amountLabel: 'Monthly Installment',
  },
  {
    id: 'spl-rd-2y',
    name: 'SPL RD — 2 Years',
    calcType: 'RD',
    supportsCustomerType: true,
    fixedTenureDays: 730,
    rates: { normal: 7.5, senior: 8.1, superSenior: 8.25 },
    minAmount: 500,
    maxAmount: 50000,
    defaultAmount: 2000,
    amountStep: 500,
    amountLabel: 'Monthly Installment',
  },
  {
    id: 'spl-rd-3y',
    name: 'SPL RD — 3 Years',
    calcType: 'RD',
    supportsCustomerType: true,
    fixedTenureDays: 1095,
    rates: { normal: 8.0, senior: 8.6, superSenior: 8.75 },
    minAmount: 500,
    maxAmount: 50000,
    defaultAmount: 2000,
    amountStep: 500,
    amountLabel: 'Monthly Installment',
  },
  {
    id: 'savings',
    name: 'Savings Deposit Account',
    calcType: 'FLAT',
    supportsCustomerType: false,
    fixedTenureDays: 365,
    rates: { normal: 3.0, senior: null, superSenior: null },
    minAmount: 1000,
    maxAmount: 500000,
    defaultAmount: 25000,
    amountStep: 1000,
    amountLabel: 'Balance',
  },
];
